<?php
function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $item['success'] = array(
        'title' => 'Encrypt',
        'page callback' => 'encrypted',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;

}

function cipher_form() {
    $form['count'] = array(
        '#title' => 'Shift Count',
        '#type' => 'textfield',
        '#description' => t('Enter the number of shifts in your message you would like.'),
        '#element_validate' => array('element_validate_number'),
        '#required' => TRUE,
    );

    $form['direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Enter the direction you would like to shift: left or right.'),
        '#element_validate' => array('element_validate_number'),
        '#required' => TRUE,
    );
    $form['message'] = array(
        '#title' => 'Message',
        '#type' => 'textfield',
        '#description' => t('Enter the message you would like to encrypt.'),
        '#element_validate' => array('element_validate_number'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encryption Time',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $count = $form_state['values']['count'];
    $direction = $form_state['values']['direction'];
    $message = $form_state['values']['message'];
    $shifting = "";

    $shifting = $message;


    $_SESSION['message_result'] = $shifting;

    $form_state['redirect'] = 'success';

}

function encrypted() {
    $encryption = $_SESSION['message_result'];
    return $encryption;
}
