<?php
function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['success'] = array(
        'title' => 'Success',
        'page callback' => 'encrypt_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;

}

function cipher_form() {
    $form['count'] = array(
        '#title' => 'Shift Count',
        '#type' => 'textfield',
        '#description' => t('Enter the number of shifts in your message you would like.'),
        '#element_validate' => array('element_validate_number'),
        '#required' => TRUE,
    );

    $form['direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'select',
        '#options' => array(
            0 => t('Left'),
            1 => t('Right'),
        ),
        '#description' => t('Select the direction you would like to shift: left or right.'),
    );
    $form['message'] = array(
        '#title' => 'Message',
        '#type' => 'textfield',
        '#description' => t('Enter the message you would like to encrypt.'),
        // '#element_validate' => array('element_validate_number'),
        // '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encryption Time',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $count = $form_state['values']['count'];
    $direction = $form_state['values']['direction'];
    $message = $form_state['values']['message'];
    $secret = array();

    $shifting = str_split($message);

    for($i = 0; $i < strlen($message); $i++){
        $letter = ord($shifting[$i]);
        $new_letter = $letter + $count;
        $here = chr($new_letter);
        array_push($secret, $here);
    }

    $secret = implode($secret);

    $_SESSION['message_result'] = $secret;


    $form_state['redirect'] = 'success';
}

function encrypt_success() {
    $encryption = $_SESSION['message_result'];
    return 'Here is the encryption: ' . $encryption;
}
